# image: https://hub.docker.com/r/bitnami/suitecrm
# docs: https://github.com/bitnami/bitnami-docker-suitecrm


version: '3.8'

services:
  suitecrm:
    image: docker.io/websoft9/suitecrm-${APP_EDITION}:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - '${APP_HTTP_PORT}:8080'
      - '${APP_HTTPS_PORT}:8443'
    environment:
      - SUITECRM_DATABASE_HOST=mysql
    volumes:
      - 'activemq:/bitnami/suitecrm'

networks:
  default:
      name: ${APP_NAME}

volumes:
  activemq:
